### ISSUE TITLE
Docker-compose volumes don't mount

### ISSUE THREAD

**Issue by a-samarin** [Parallels/docker-machine-parallels#88]
Hello!
I have a docker-compose that I'm using to build Django + React project. 

Yesterday I've wanted to change some staff and figured out that project didn't build. After some investigation I found that volumes don't mount at all (for django and and react frontend)

I'm using this scheme

```
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.backend
    ports:
      - "8000:8000"
    entrypoint: /backend.sh
    volumes:
      - ./api:/backend
```

1. I tried to change the path to "full path" or @PWD/api - didn't help. 
2. I have Version 15.1.3 (47255)

<img width="584" alt="Screenshot 2020-04-21 at 17 05 14" src="https://user-images.githubusercontent.com/3470768/79854500-b7abc280-83f3-11ea-83fc-c361e8a0b6e0.png">

<img width="698" alt="Screenshot 2020-04-21 at 17 06 34" src="https://user-images.githubusercontent.com/3470768/79854514-bd090d00-83f3-11ea-9caf-b9b07abce62d.png">

3. When I removed the volumes mountings and copied the code directly inside the Dockerfile.backend file it started to work, but I would like to keep the advantage of mounting folders during coding, because in this case I don't need to build project every time I change something in UI (React) project

Any suggestions how to fix this?
